from typing import Any, TypeVar, Union

_T = TypeVar("_T", bound="DataClassJsonMixin")

class DataClassJsonMixin:
    def to_json(self, *, skipkeys: bool = ..., ensure_ascii: bool = ..., check_circular: bool = ..., allow_nan: bool = ..., indent: int | str | None = ..., separators: tuple[str, str] | None = ..., default: Any = ..., sort_keys: bool = ..., **kw: Any) -> str: ...
    @classmethod
    def from_json(cls: type[_T], s: str | bytes | bytearray, *, parse_float: Any = ..., parse_int: Any = ..., parse_constant: Any = ..., infer_missing: bool = ..., **kw: Any) -> _T: ...
    def to_dict(self, encode_json: bool = ...) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls: type[_T], kvs: Any, *, infer_missing: bool = ...) -> _T: ...
